# Generated by Django 5.0.2 on 2024-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('task_desc', models.CharField(max_length=30)),
                ('date_added', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
